# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `Client` directory
    directory: "/WebClient/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for dotnet
  - package-ecosystem: "nuget"
    # Look for package files in the `ApiServer` directory
    directory: "/ApiServer/"
    # Check the for updates every Wednesday
    schedule:
      interval: "daily"
